⬆️(deps): Update dependency org.testcontainers:testcontainers-bom to v1.15.2 (#260)
⬆️(deps): Update dependency org.testcontainers:testcontainers-bom to v1.15.2

[![WhiteSource Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.testcontainers:testcontainers-bom](https://testcontainers.org) ([source](https://togithub.com/testcontainers/testcontainers-java)) | `1.15.1` -> `1.15.2` | [![age](https://badges.renovateapi.com/packages/maven/org.testcontainers:testcontainers-bom/1.15.2/age-slim)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://badges.renovateapi.com/packages/maven/org.testcontainers:testcontainers-bom/1.15.2/adoption-slim)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://badges.renovateapi.com/packages/maven/org.testcontainers:testcontainers-bom/1.15.2/compatibility-slim/1.15.1)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://badges.renovateapi.com/packages/maven/org.testcontainers:testcontainers-bom/1.15.2/confidence-slim/1.15.1)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>testcontainers/testcontainers-java</summary>

### [`v1.15.2`](https://togithub.com/testcontainers/testcontainers-java/releases/1.15.2)

[Compare Source](https://togithub.com/testcontainers/testcontainers-java/compare/1.15.1...1.15.2)

##### What's Changed

-   What `1984` means to you? To us, this number means PR [#&#8203;1984](https://togithub.com/testcontainers/testcontainers-java/issues/1984), one of the oldest PRs we had open and... finally merged! 😅 Thanks to an amazing contribution by [@&#8203;seglo](https://togithub.com/seglo), we now provide an example of testing Kafka clusters where multiple `KafkaContainer`s are connected into one network. Try it!
-   Another "old" PR is [#&#8203;3180](https://togithub.com/testcontainers/testcontainers-java/issues/3180) by [@&#8203;oussamabadr](https://togithub.com/oussamabadr). Those of you who run Selenium tests with Testcontainers will appreciate this newly added option to use (scrollable!) MP4 format instead of FLV.
-   The connection with Ryuk (our watchdog sidecar container) now sets the socket timeout and retries the failures - helps with some rare networking edge cases. ([#&#8203;3682](https://togithub.com/testcontainers/testcontainers-java/issues/3682)) [@&#8203;diegolovison](https://togithub.com/diegolovison)
-   The logs consumer no longer adds extra new lines thanks to [#&#8203;3752](https://togithub.com/testcontainers/testcontainers-java/issues/3752) by [@&#8203;perlun](https://togithub.com/perlun)
-   Locally built images no longer get affected by the `hub.image.name.prefix` setting! ([#&#8203;3666](https://togithub.com/testcontainers/testcontainers-java/issues/3666)) [@&#8203;reda-alaoui](https://togithub.com/reda-alaoui)
-   Jackson dependency is now forced to an older version to help with `NoClassDefFoundError (com/fasterxml/jackson/annotation/JsonMerge)`.

And more!

##### 🚀 Features & Enhancements

-   Switch to Presto image hosted on GHCR ([#&#8203;3667](https://togithub.com/testcontainers/testcontainers-java/issues/3667)) [@&#8203;findepi](https://togithub.com/findepi)
-   Implement getDatabaseName() in CockroachContainer ([#&#8203;3778](https://togithub.com/testcontainers/testcontainers-java/issues/3778)) [@&#8203;croemmich](https://togithub.com/croemmich)
-   Make recorder .flv videos scrollable ([#&#8203;512](https://togithub.com/testcontainers/testcontainers-java/issues/512)) ([#&#8203;3180](https://togithub.com/testcontainers/testcontainers-java/issues/3180)) [@&#8203;oussamabadr](https://togithub.com/oussamabadr)
-   Support HTTP headers on HttpWaitStrategy ([#&#8203;2549](https://togithub.com/testcontainers/testcontainers-java/issues/2549)) [@&#8203;renatomefi](https://togithub.com/renatomefi)
-   Show port mappings in HttpWaitStrategy ([#&#8203;2341](https://togithub.com/testcontainers/testcontainers-java/issues/2341)) [@&#8203;aguibert](https://togithub.com/aguibert)
-   Support newer versions of CockroachDB by changing the docker command ([#&#8203;3608](https://togithub.com/testcontainers/testcontainers-java/issues/3608)) [@&#8203;giger85](https://togithub.com/giger85)
-   Improve logging for port listener ([#&#8203;3736](https://togithub.com/testcontainers/testcontainers-java/issues/3736)) [@&#8203;artjomka](https://togithub.com/artjomka)
-   couchbase: wait until all services are part of the config ([#&#8203;3003](https://togithub.com/testcontainers/testcontainers-java/issues/3003)) [@&#8203;daschl](https://togithub.com/daschl)
-   Support Ryuk socket timeout ([#&#8203;3682](https://togithub.com/testcontainers/testcontainers-java/issues/3682)) [@&#8203;diegolovison](https://togithub.com/diegolovison)
-   Add init command parameter to Vault container ([#&#8203;3188](https://togithub.com/testcontainers/testcontainers-java/issues/3188)) [@&#8203;tandrup](https://togithub.com/tandrup)
-   Startables#deepStart with varargs ([#&#8203;3261](https://togithub.com/testcontainers/testcontainers-java/issues/3261)) [@&#8203;jochenchrist](https://togithub.com/jochenchrist)

##### 🐛 Bug Fixes

-   Remove extra newlines in container log output ([#&#8203;3752](https://togithub.com/testcontainers/testcontainers-java/issues/3752)) [@&#8203;perlun](https://togithub.com/perlun)
-   Fix handling of locally built images when used with `hub.image.name.prefix` ([#&#8203;3666](https://togithub.com/testcontainers/testcontainers-java/issues/3666)) [@&#8203;reda-alaoui](https://togithub.com/reda-alaoui)

##### 📖 Documentation

-   Kafka cluster example ([#&#8203;1984](https://togithub.com/testcontainers/testcontainers-java/issues/1984), [#&#8203;3758](https://togithub.com/testcontainers/testcontainers-java/issues/3758)) [@&#8203;seglo](https://togithub.com/seglo)
-   Documentation PostGIS JDBC url sample version update ([#&#8203;3606](https://togithub.com/testcontainers/testcontainers-java/issues/3606)) [@&#8203;aulea](https://togithub.com/aulea)
-   GenericContainer: fix typo in Javadoc ([#&#8203;3684](https://togithub.com/testcontainers/testcontainers-java/issues/3684)) [@&#8203;perlun](https://togithub.com/perlun)
-   Added documentation for Bigtable Emulator container ([#&#8203;3708](https://togithub.com/testcontainers/testcontainers-java/issues/3708)) [@&#8203;RamazanYapparov](https://togithub.com/RamazanYapparov)
-   Clarify usage of host port exporting ([#&#8203;3421](https://togithub.com/testcontainers/testcontainers-java/issues/3421)) [@&#8203;alxgrk](https://togithub.com/alxgrk)
-   Rename Presto to Trino ([#&#8203;3649](https://togithub.com/testcontainers/testcontainers-java/issues/3649)) [@&#8203;martint](https://togithub.com/martint)

##### 🧹 Housekeeping

-   update release drafter to v5.13.0 ([#&#8203;3632](https://togithub.com/testcontainers/testcontainers-java/issues/3632)) [@&#8203;jetersen](https://togithub.com/jetersen)
-   Remove duplicated dependency in jdbc-test module ([#&#8203;3664](https://togithub.com/testcontainers/testcontainers-java/issues/3664)) [@&#8203;giger85](https://togithub.com/giger85)
-   add github actions to dependabot config ([#&#8203;3633](https://togithub.com/testcontainers/testcontainers-java/issues/3633)) [@&#8203;jetersen](https://togithub.com/jetersen)
-   Remove ciMate ([#&#8203;3631](https://togithub.com/testcontainers/testcontainers-java/issues/3631)) [@&#8203;bsideup](https://togithub.com/bsideup)

##### 📦 Dependency updates

-   update release drafter to v5.13.0 ([#&#8203;3632](https://togithub.com/testcontainers/testcontainers-java/issues/3632)) [@&#8203;jetersen](https://togithub.com/jetersen)
-   Force Jackson version ([#&#8203;3602](https://togithub.com/testcontainers/testcontainers-java/issues/3602)) [@&#8203;bsideup](https://togithub.com/bsideup)
-   Bump aws-java-sdk-sqs from 1.11.884 to 1.11.930 in /modules/localstack ([#&#8203;3660](https://togithub.com/testcontainers/testcontainers-java/issues/3660)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump guava from 30.0-jre to 30.1-jre in /modules/jdbc-test ([#&#8203;3622](https://togithub.com/testcontainers/testcontainers-java/issues/3622)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump aws-java-sdk-s3 from 1.11.929 to 1.11.930 in /modules/localstack ([#&#8203;3659](https://togithub.com/testcontainers/testcontainers-java/issues/3659)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump org.jetbrains.kotlin.plugin.spring from 1.3.31 to 1.4.21-2 in /examples ([#&#8203;3646](https://togithub.com/testcontainers/testcontainers-java/issues/3646)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump gradle-update/update-gradle-wrapper-action from [`74a035c`](https://togithub.com/testcontainers/testcontainers-java/commit/74a035c) to 1.0.9 ([#&#8203;3653](https://togithub.com/testcontainers/testcontainers-java/issues/3653)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump cucumber-junit from 6.8.1 to 6.9.1 in /examples ([#&#8203;3625](https://togithub.com/testcontainers/testcontainers-java/issues/3625)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump testcontainers from 1.14.3 to 1.15.1 in /core ([#&#8203;3587](https://togithub.com/testcontainers/testcontainers-java/issues/3587)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump transport from 7.10.0 to 7.10.1 in /modules/elasticsearch ([#&#8203;3590](https://togithub.com/testcontainers/testcontainers-java/issues/3590)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump aws-java-sdk-s3 from 1.11.882 to 1.11.929 in /modules/localstack ([#&#8203;3654](https://togithub.com/testcontainers/testcontainers-java/issues/3654)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump s3 from 2.15.14 to 2.15.56 in /modules/localstack ([#&#8203;3650](https://togithub.com/testcontainers/testcontainers-java/issues/3650)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump org.jetbrains.kotlin.jvm from 1.3.31 to 1.4.21-2 in /examples ([#&#8203;3645](https://togithub.com/testcontainers/testcontainers-java/issues/3645)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump guava from 30.0-jre to 30.1-jre in /core ([#&#8203;3627](https://togithub.com/testcontainers/testcontainers-java/issues/3627)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump ad-m/github-push-action from [`68af989`](https://togithub.com/testcontainers/testcontainers-java/commit/68af9897f2b021035ca3952bf354bbb4675c1762) to 0.6.0 ([#&#8203;3658](https://togithub.com/testcontainers/testcontainers-java/issues/3658)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump aws-java-sdk-dynamodb from 1.11.901 to 1.11.929 in /modules/dynalite ([#&#8203;3652](https://togithub.com/testcontainers/testcontainers-java/issues/3652)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump gradle/wrapper-validation-action from [`e2c57ac`](https://togithub.com/testcontainers/testcontainers-java/commit/e2c57ac) to 1.0.3 ([#&#8203;3657](https://togithub.com/testcontainers/testcontainers-java/issues/3657)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Update actions/cache requirement to v2.1.3 ([#&#8203;3651](https://togithub.com/testcontainers/testcontainers-java/issues/3651)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump solr-solrj from 8.6.3 to 8.7.0 in /examples ([#&#8203;3446](https://togithub.com/testcontainers/testcontainers-java/issues/3446)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump cucumber-java from 6.8.1 to 6.9.1 in /examples ([#&#8203;3624](https://togithub.com/testcontainers/testcontainers-java/issues/3624)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump r2dbc-mariadb from 0.8.4-rc to 1.0.0 in /modules/mariadb ([#&#8203;3593](https://togithub.com/testcontainers/testcontainers-java/issues/3593)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump org.springframework.boot from 2.3.4.RELEASE to 2.4.1 in /examples ([#&#8203;3594](https://togithub.com/testcontainers/testcontainers-java/issues/3594)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump jedis from 3.3.0 to 3.4.0 in /examples ([#&#8203;3595](https://togithub.com/testcontainers/testcontainers-java/issues/3595)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump tomcat-jdbc from 9.0.40 to 10.0.0 in /modules/jdbc ([#&#8203;3592](https://togithub.com/testcontainers/testcontainers-java/issues/3592)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump elasticsearch-rest-client from 7.10.0 to 7.10.1 in /modules/elasticsearch ([#&#8203;3589](https://togithub.com/testcontainers/testcontainers-java/issues/3589)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump jedis from 3.3.0 to 3.4.0 in /core ([#&#8203;3586](https://togithub.com/testcontainers/testcontainers-java/issues/3586)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump rest-assured from 4.3.1 to 4.3.3 in /modules/vault ([#&#8203;3588](https://togithub.com/testcontainers/testcontainers-java/issues/3588)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump r2dbc-mssql from 0.8.4.RELEASE to 0.8.5.RELEASE in /modules/mssqlserver ([#&#8203;3397](https://togithub.com/testcontainers/testcontainers-java/issues/3397)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump mockito-core from 3.5.15 to 3.6.28 in /modules/junit-jupiter ([#&#8203;3539](https://togithub.com/testcontainers/testcontainers-java/issues/3539)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump mockito-core from 3.5.13 to 3.6.28 in /core ([#&#8203;3542](https://togithub.com/testcontainers/testcontainers-java/issues/3542)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump mssql-jdbc from 9.1.0.jre8-preview to 9.1.1.jre8-preview in /modules/mssqlserver ([#&#8203;3563](https://togithub.com/testcontainers/testcontainers-java/issues/3563)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump pulsar-client-admin from 2.6.1 to 2.7.0 in /modules/pulsar ([#&#8203;3566](https://togithub.com/testcontainers/testcontainers-java/issues/3566)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump pulsar-client from 2.6.1 to 2.7.0 in /modules/pulsar ([#&#8203;3565](https://togithub.com/testcontainers/testcontainers-java/issues/3565)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump json from [`2018081`](https://togithub.com/testcontainers/testcontainers-java/commit/20180813) to [`2020111`](https://togithub.com/testcontainers/testcontainers-java/commit/20201115) in /examples ([#&#8203;3567](https://togithub.com/testcontainers/testcontainers-java/issues/3567)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump influxdb-java from 2.20 to 2.21 in /modules/influxdb ([#&#8203;3568](https://togithub.com/testcontainers/testcontainers-java/issues/3568)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Bump assertj-core from 3.18.0 to 3.18.1 in /modules/vault ([#&#8203;3486](https://togithub.com/testcontainers/testcontainers-java/issues/3486)) [@&#8203;dependabot](https://togithub.com/dependabot)
-   Upgrade Ryuk to 0.3.1 ([#&#8203;3629](https://togithub.com/testcontainers/testcontainers-java/issues/3629)) [@&#8203;rnorth](https://togithub.com/rnorth)

</details>

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#github/team-kaba/selidor).