⬆️(deps): Update spring boot to v2.2.3.RELEASE (#113)
⬆️(deps): Update spring boot to v2.2.3.RELEASE

This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [org.springframework.boot:spring-boot-dependencies](https://projects.spring.io/spring-boot/#) ([source](https://togithub.com/spring-projects/spring-boot)) | patch | `2.2.2.RELEASE` -> `2.2.3.RELEASE` |
| [org.springframework.boot:spring-boot-starter-test](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-starters/spring-boot-starter-test) ([source](https://togithub.com/spring-projects/spring-boot)) | patch | `2.2.2.RELEASE` -> `2.2.3.RELEASE` |
| [org.springframework.boot:spring-boot-maven-plugin](https://projects.spring.io/spring-boot/#/spring-boot-parent/spring-boot-tools/spring-boot-maven-plugin) ([source](https://togithub.com/spring-projects/spring-boot)) | patch | `2.2.2.RELEASE` -> `2.2.3.RELEASE` |

---

### Release Notes

<details>
<summary>spring-projects/spring-boot</summary>

### [`v2.2.3.RELEASE`](https://togithub.com/spring-projects/spring-boot/releases/v2.2.3.RELEASE)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.2.2.RELEASE...v2.2.3.RELEASE)

#### :star: New Features

-   Avoid 406 Not Acceptable for error pages [#&#8203;19545](https://togithub.com/spring-projects/spring-boot/issues/19545)
-   Ignore trailing slash by default when recording web metrics [#&#8203;18207](https://togithub.com/spring-projects/spring-boot/issues/18207)

#### :beetle: Bug Fixes

-   Fat jars do not tolerate entries with an invalid modification date of 0 [#&#8203;19713](https://togithub.com/spring-projects/spring-boot/issues/19713)
-   Make equality checks defensive to null reference [#&#8203;19685](https://togithub.com/spring-projects/spring-boot/issues/19685)
-   PoolingDataSourceBean getParentLogger throws StackOverflowError [#&#8203;19682](https://togithub.com/spring-projects/spring-boot/issues/19682)
-   Failure analyser for a missing validation provider does not kick in when using the latest Jakarta Validation API [#&#8203;19671](https://togithub.com/spring-projects/spring-boot/issues/19671)
-   Rejected value is null when configuration property fails validation [#&#8203;19580](https://togithub.com/spring-projects/spring-boot/issues/19580)
-   Profile with comma in name does not work in tests [#&#8203;19560](https://togithub.com/spring-projects/spring-boot/issues/19560)
-   Spring Boot's antlib references a properties file that is no longer packaged in its jar [#&#8203;19553](https://togithub.com/spring-projects/spring-boot/issues/19553)
-   Incorrect target type with wildcard List [#&#8203;19526](https://togithub.com/spring-projects/spring-boot/issues/19526)
-   Since 2.2.2 Jetty error handler cannot be overridden [#&#8203;19520](https://togithub.com/spring-projects/spring-boot/issues/19520)
-   Use RBAC credentials for Couchbase cluster info [#&#8203;19393](https://togithub.com/spring-projects/spring-boot/issues/19393)
-   HypermediaAutoConfiguration hinges on Spring MVC [#&#8203;19392](https://togithub.com/spring-projects/spring-boot/issues/19392)
-   Micrometer's Dynatrace group property cannot be configured via application properties [#&#8203;19369](https://togithub.com/spring-projects/spring-boot/pull/19369)
-   MetricsWebFilter assigns UNKNOWN outcome to 200 OK responses [#&#8203;19367](https://togithub.com/spring-projects/spring-boot/issues/19367)
-   Disable Jackson SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS by default [#&#8203;19352](https://togithub.com/spring-projects/spring-boot/pull/19352)
-   Unset forward header strategy in kubernetes environment eats X-Forwarded-\* headers in Spring Boot 2.2 [#&#8203;19333](https://togithub.com/spring-projects/spring-boot/issues/19333)
-   Diagnostics are poor when using `@ConfigurationPropertiesScan` and `@ConstructorBinding` on a Kotlin data class without kotlin-reflect [#&#8203;19312](https://togithub.com/spring-projects/spring-boot/issues/19312)
-   NoSuchMethodError when deploying to Tomcat 8.5 before 8.5.44 and Tomcat 9 before 9.0.23 [#&#8203;19308](https://togithub.com/spring-projects/spring-boot/issues/19308)
-   Non-public property in Saml2RelyingPartyProperties' Registration class [#&#8203;19194](https://togithub.com/spring-projects/spring-boot/issues/19194)
-   Configuration properties that use the builder pattern are not recognized when used with a generic [#&#8203;19099](https://togithub.com/spring-projects/spring-boot/pull/19099)
-   Support commas embedded in command line arguments from Maven plugin [#&#8203;18711](https://togithub.com/spring-projects/spring-boot/pull/18711)

#### :notebook_with_decorative_cover: Documentation

-   Remove duplicate note in Hazelcast section of reference guide [#&#8203;19678](https://togithub.com/spring-projects/spring-boot/issues/19678)
-   Fix links to external types in javadoc [#&#8203;19591](https://togithub.com/spring-projects/spring-boot/issues/19591)
-   Links to apply method in AutoTimer's javadoc are broken [#&#8203;19572](https://togithub.com/spring-projects/spring-boot/issues/19572)
-   Spring MVC auto-config doc update [#&#8203;19521](https://togithub.com/spring-projects/spring-boot/pull/19521)
-   Add reference to OptaPlanner starter [#&#8203;19508](https://togithub.com/spring-projects/spring-boot/pull/19508)
-   Outdated reference in ArtemisConfigurationCustomizer javadoc [#&#8203;19503](https://togithub.com/spring-projects/spring-boot/pull/19503)
-   Polish note about handling of caches that are created on-the-fly [#&#8203;19498](https://togithub.com/spring-projects/spring-boot/issues/19498)
-   Fix typo in BindHandler#onFinish javadoc [#&#8203;19496](https://togithub.com/spring-projects/spring-boot/issues/19496)
-   Adapt file rotation documentation to logging's maxHistory default change to 7 days [#&#8203;19458](https://togithub.com/spring-projects/spring-boot/pull/19458)
-   Clarify documentation of repackage mojo's attach property [#&#8203;19453](https://togithub.com/spring-projects/spring-boot/issues/19453)
-   Clarify non-public nature of Boot?s own [@&#8203;ConfigurationProperties](https://togithub.com/ConfigurationProperties) classes and multi-DataSource example [#&#8203;19451](https://togithub.com/spring-projects/spring-boot/issues/19451)
-   Clarify the behaviour of [@&#8203;CacheConfig](https://togithub.com/CacheConfig) with respect to on-the-fly cache creation and cache metrics [#&#8203;19448](https://togithub.com/spring-projects/spring-boot/issues/19448)
-   Add JMX note for Kafka consumer metrics [#&#8203;19446](https://togithub.com/spring-projects/spring-boot/pull/19446)
-   Fix typo on ConditionMessage [#&#8203;19433](https://togithub.com/spring-projects/spring-boot/issues/19433)
-   Improve "Running Behind a Front-end Proxy Server" documentation [#&#8203;19403](https://togithub.com/spring-projects/spring-boot/issues/19403)
-   Link consistently to Tomcat 9.0 docs [#&#8203;19362](https://togithub.com/spring-projects/spring-boot/issues/19362)
-   Fix link to Vaadin Spring Boot starter [#&#8203;19360](https://togithub.com/spring-projects/spring-boot/issues/19360)
-   Improve documentation coverage for Spring Batch [#&#8203;19211](https://togithub.com/spring-projects/spring-boot/pull/19211)

#### :hammer: Dependency Upgrades

-   Upgrade to Micrometer 1.3.2 [#&#8203;19778](https://togithub.com/spring-projects/spring-boot/issues/19778)
-   Upgrade to Spring Retry 1.2.5.RELEASE [#&#8203;19758](https://togithub.com/spring-projects/spring-boot/issues/19758)
-   Upgrade to Slf4j 1.7.30 [#&#8203;19757](https://togithub.com/spring-projects/spring-boot/issues/19757)
-   Upgrade to Postgresql 42.2.9 [#&#8203;19756](https://togithub.com/spring-projects/spring-boot/issues/19756)
-   Upgrade to Neo4j Ogm 3.2.6 [#&#8203;19755](https://togithub.com/spring-projects/spring-boot/issues/19755)
-   Upgrade to Liquibase 3.8.5 [#&#8203;19754](https://togithub.com/spring-projects/spring-boot/issues/19754)
-   Upgrade to Kotlin Coroutines 1.3.3 [#&#8203;19753](https://togithub.com/spring-projects/spring-boot/issues/19753)
-   Upgrade to Infinispan 9.4.17.Final [#&#8203;19752](https://togithub.com/spring-projects/spring-boot/issues/19752)
-   Upgrade to Hibernate 5.4.10.Final [#&#8203;19751](https://togithub.com/spring-projects/spring-boot/issues/19751)
-   Upgrade to Elasticsearch 6.8.6 [#&#8203;19750](https://togithub.com/spring-projects/spring-boot/issues/19750)
-   Upgrade to Jetty 9.4.25.v20191220 [#&#8203;19749](https://togithub.com/spring-projects/spring-boot/issues/19749)
-   Upgrade to Groovy 2.5.9 [#&#8203;19748](https://togithub.com/spring-projects/spring-boot/issues/19748)
-   Upgrade to Awaitility 4.0.2 [#&#8203;19747](https://togithub.com/spring-projects/spring-boot/issues/19747)
-   Upgrade to Httpcore 4.4.13 [#&#8203;19746](https://togithub.com/spring-projects/spring-boot/issues/19746)
-   Upgrade to Byte Buddy 1.10.6 [#&#8203;19745](https://togithub.com/spring-projects/spring-boot/issues/19745)
-   Upgrade to Mysql 8.0.19 [#&#8203;19744](https://togithub.com/spring-projects/spring-boot/issues/19744)
-   Upgrade to Undertow 2.0.29.Final [#&#8203;19743](https://togithub.com/spring-projects/spring-boot/issues/19743)
-   Upgrade to Rxjava2 2.2.17 [#&#8203;19742](https://togithub.com/spring-projects/spring-boot/issues/19742)
-   Upgrade to Netty 4.1.45.Final [#&#8203;19741](https://togithub.com/spring-projects/spring-boot/issues/19741)
-   Upgrade to Dropwizard Metrics 4.1.2 [#&#8203;19740](https://togithub.com/spring-projects/spring-boot/issues/19740)
-   Upgrade to Hikaricp 3.4.2 [#&#8203;19739](https://togithub.com/spring-projects/spring-boot/issues/19739)
-   Upgrade to Unboundid Ldapsdk 4.0.14 [#&#8203;19738](https://togithub.com/spring-projects/spring-boot/issues/19738)
-   Upgrade to Okhttp3 3.14.6 [#&#8203;19737](https://togithub.com/spring-projects/spring-boot/issues/19737)
-   Upgrade to Hazelcast 3.12.5 [#&#8203;19736](https://togithub.com/spring-projects/spring-boot/issues/19736)
-   Upgrade to Jackson 2.10.2 [#&#8203;19735](https://togithub.com/spring-projects/spring-boot/issues/19735)
-   Upgrade to Jakarta Validation API 2.0.2 [#&#8203;19687](https://togithub.com/spring-projects/spring-boot/issues/19687)
-   Upgrade to Spring Data Moore-SR4 [#&#8203;19648](https://togithub.com/spring-projects/spring-boot/issues/19648)
-   Upgrade to Spring Integration 5.2.3 [#&#8203;19647](https://togithub.com/spring-projects/spring-boot/issues/19647)
-   Upgrade to Spring AMQP 2.2.3 [#&#8203;19646](https://togithub.com/spring-projects/spring-boot/issues/19646)
-   Upgrade to Spring HATEOAS 1.0.3 [#&#8203;19644](https://togithub.com/spring-projects/spring-boot/issues/19644)
-   Upgrade to Reactor Dysprosium-SR3 [#&#8203;19643](https://togithub.com/spring-projects/spring-boot/issues/19643)
-   Upgrade to Spring Kafka 2.3.5 [#&#8203;19613](https://togithub.com/spring-projects/spring-boot/issues/19613)
-   Upgrade to Spring Framework 5.2.3 [#&#8203;19531](https://togithub.com/spring-projects/spring-boot/issues/19531)
-   Upgrade to nohttp 0.0.4.RELEASE [#&#8203;19479](https://togithub.com/spring-projects/spring-boot/issues/19479)
-   Upgrade to Tomcat 9.0.30 [#&#8203;19473](https://togithub.com/spring-projects/spring-boot/issues/19473)

#### :heart: Contributors

We'd like to thank all the contributors who worked on this release!

-   [@&#8203;dreis2211](https://togithub.com/dreis2211)
-   [@&#8203;Dark0096](https://togithub.com/Dark0096)
-   [@&#8203;filiphr](https://togithub.com/filiphr)
-   [@&#8203;gintellect79](https://togithub.com/gintellect79)
-   [@&#8203;nosan](https://togithub.com/nosan)
-   [@&#8203;ChunMengLu](https://togithub.com/ChunMengLu)
-   [@&#8203;fjacobs](https://togithub.com/fjacobs)
-   [@&#8203;izeye](https://togithub.com/izeye)
-   [@&#8203;aklish](https://togithub.com/aklish)
-   [@&#8203;Buzzardo](https://togithub.com/Buzzardo)
-   [@&#8203;ge0ffrey](https://togithub.com/ge0ffrey)
-   [@&#8203;rstoyanchev](https://togithub.com/rstoyanchev)
-   [@&#8203;ochiengolanga](https://togithub.com/ochiengolanga)

</details>

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Whenever PR becomes conflicted, or if you modify the PR title to begin with "`rebase!`".

:no_bell: **Ignore**: Close this PR and you won't be reminded about these updates again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#team-kaba/selidor).